### ISSUE TITLE
Validation of Different Validators

### ISSUE THREAD

**Issue by eduardomfarias** [idsulik/helm-cel#4]
Would it be possible to create a way to have different validators?

For rule creation, a YAML file called values.cel.yaml is used, containing all the rules we want to define. However, it would be interesting if we could separate the rules into different files, for example:

global.cel.yaml
ingress.cel.yaml
deployments.cel.yaml
The names could be freely chosen, as long as Helm CEL recognizes the .cel.yaml extension.

This would make organizing validation rules easier.

Another case would be pointing to the values file we want to validate. In the current format, Helm CEL only validates the values.yaml in the same directory as values.cel.yaml. It would be interesting if we could do something like this:

```helm cel . -f ./path/values.yaml```

Do you think these two updates would be possible?

**Comment by idsulik** [comment]
@eduardomfarias , you can specify custom values-file and rules-file, for example:
`helm cel validate ./mychart --values-file prod.values.yaml --rules-file prod.cel.yaml`. 

good idea about the different files, I think I'll implement it soon(or you can do it by yourself if you want). And, accept multiple custom values/rules files as well

**Comment by eduardomfarias** [comment]
```helm cel validate ./mychart --values-file prod.values.yaml --rules-file prod.cel.yaml```

This function is not available yet. I updated the plugin, but it is still not possible to use it.

![image](https://github.com/user-attachments/assets/f6409200-3d18-480d-adde-03a439bb6b83)

**Comment by idsulik** [comment]
@eduardomfarias try `--values-file`

**Comment by idsulik** [comment]
@eduardomfarias hi! Let me know pls if it helped or not

**Comment by idsulik** [comment]
@eduardomfarias hi! Multiple values/rules support was added to the latest version https://github.com/idsulik/helm-cel/releases/tag/v2.1.0
